import React, { useState } from 'react';
import {
  View,
  Text,
  StyleSheet,
  SafeAreaView,
  TouchableOpacity,
  Image,
  useWindowDimensions,
  ActivityIndicator,
  Alert,
} from 'react-native';
import { useRouter } from 'expo-router';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import GradientBackground from '../components/GradientBackground';
import Button from '../components/ui/Button';
import Card from '../components/ui/Card';
import { Ionicons } from '@expo/vector-icons';


export default function CreateSessionScreen() {
  const router = useRouter();
  const insets = useSafeAreaInsets();
  const { height } = useWindowDimensions();

  // 6-cijferige code voor scherm (will be generated by backend)
  const [sessionCode] = useState(
    Math.floor(100000 + Math.random() * 900000).toString()
  );

  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  // Dynamische hoogte van de hero
  const HERO_HEIGHT = height * 0.28;

  const handleCreateSession = async () => {
    if (loading) return;

    setLoading(true);
    setError(null);

    try {
      // Navigate directly to consent screen where session will be created
      // This allows the user to enter their name and session details first
      router.push(`/consent?mode=host`);
    } catch (e) {
      console.error('Create session error:', e);
      setError('Er ging iets mis bij het aanmaken van de sessie. Probeer het nog een keer.');
      Alert.alert('Fout', 'Er ging iets mis bij het aanmaken van de sessie. Probeer het opnieuw.');
    } finally {
      setLoading(false);
    }
  };


  return (
    <GradientBackground>
      {/* Watermark gecentreerd in hero-blok */}
      <Image
        source={{
          uri: 'https://d64gsuwffb70l.cloudfront.net/686d5a4b47ae519b1741842d_1763759081415_4b7dbe8a.png',
        }}
        style={[
          styles.watermark,
          {
            top: insets.top + HERO_HEIGHT * 0.12,
            width: HERO_HEIGHT * 0.95,
            height: HERO_HEIGHT * 0.95,
          },
        ]}
        resizeMode="contain"
      />

      <SafeAreaView style={styles.container}>
        {/* Terugknop */}
        <TouchableOpacity
          style={[styles.backButton, { top: insets.top + 8 }]}
          onPress={() => router.back()}
        >
          <Ionicons name="arrow-back" size={28} color="#121212" />
        </TouchableOpacity>

        {/* HERO BLOCK */}
        <View
          style={{
            height: HERO_HEIGHT,
            justifyContent: 'flex-end',
            alignItems: 'center',
          }}
        >
          <Text style={styles.title}>Nieuwe sessie</Text>
        </View>

        {/* CARD BLOCK */}
        <View style={styles.cardWrapper}>
          <Card style={styles.card}>
            <Text style={styles.label}>Start een nieuwe sessie</Text>

            <Text style={styles.hint}>
              Klik op "Doorgaan" om een nieuwe sessie aan te maken. Je krijgt dan een unieke code die je kunt delen met deelnemers.
            </Text>

            {error && <Text style={styles.error}>{error}</Text>}

            <Button
              title={loading ? 'Bezig…' : 'Doorgaan'}
              onPress={handleCreateSession}
              style={styles.button}
            />

            {loading && (
              <View style={styles.loaderRow}>
                <ActivityIndicator size="small" />
                <Text style={styles.loaderText}>Sessie wordt aangemaakt…</Text>
              </View>
            )}
          </Card>
        </View>
      </SafeAreaView>
    </GradientBackground>
  );
}

const styles = StyleSheet.create({
  container: { flex: 1 },

  watermark: {
    position: 'absolute',
    opacity: 0.3,
    zIndex: 0,
    alignSelf: 'center',
  },

  backButton: {
    position: 'absolute',
    left: 20,
    zIndex: 20,
    padding: 8,
  },

  title: {
    fontSize: 28,
    fontWeight: '700',
    color: '#121212',
    textAlign: 'center',
    marginBottom: 8,
  },

  cardWrapper: {
    flex: 1,
    paddingHorizontal: 20,
    paddingTop: 8,
  },

  card: {
    padding: 20,
    borderRadius: 20,
    backgroundColor: 'rgba(255,255,255,0.96)',
  },

  label: {
    fontSize: 16,
    fontWeight: '600',
    color: '#121212',
    marginBottom: 12,
    textAlign: 'center',
  },

  hint: {
    fontSize: 14,
    color: '#555',
    textAlign: 'center',
    marginTop: 4,
    lineHeight: 20,
  },

  button: {
    marginTop: 24,
  },

  error: {
    marginTop: 12,
    color: '#D7263D',
    textAlign: 'center',
    fontSize: 13,
  },

  loaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 12,
    gap: 8,
  },

  loaderText: {
    marginLeft: 8,
    fontSize: 13,
    color: '#555',
  },
});
